spring:
  application:
    name: ms-discovery

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    #prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 5
    #lease-expiration-duration-in-seconds: 10
  server:
    renewal-percent-threshold: 0.90
  client:
    fetch-registry: false
    register-with-eureka: false
    #healthcheck:
      #enabled: true
    #service-url:
      #defaultZone: http://${EUREKA_SERVER_DOMAIN}:${PORT_EUREKA}/eureka

#logging:
  #level:
    #org.springframework.security: DEBUG


